[package]
name = "bonkbot"
version = "2.1.0"
authors = ["Jamie Quigley <jamie@quigley.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
rand = "0.8.5"
reqwest = "0.11.9"
tokio = {version = "1.16", features = ["macros", "rt-multi-thread"]}
clap = { version = "3.0.14", features = ["derive"] }
tracing = "0.1.30"
tracing-subscriber = "0.3.8"

[dependencies.serenity]
default-features=false
features=["client", "gateway", "rustls_backend", "model", "cache", "unstable_discord_api"]
version = "0.11.1"

[features]
