[package]
name = "bonkbot"
version = "2.1.0"
authors = ["Jamie Quigley <jamie@quigley.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
rand = "0.8.4"
reqwest = "0.11.8"
structopt = "0.3"
tokio = {version = "1.15", features = ["macros", "rt-multi-thread"]}
once_cell = "1.9.0"
tracing = "0.1.29"
tracing-subscriber = "0.3.4"

[dependencies.serenity]
default-features=false
features=["client", "gateway", "rustls_backend", "model", "cache", "unstable_discord_api"]
version = "0.10.9"
